language: elixir

# Build Matrix (https://git.io/fjbbL)
matrix:
  include:
    # Elixir 1.7 with OTP 20-21
    - elixir: 1.7.0
      otp_release: 20.0
    - elixir: 1.7.0
      otp_release: 21.0

    # Elixir 1.8 with OTP 20-22
    - elixir: 1.8.0
      otp_release: 20.0
    - elixir: 1.8.0
      otp_release: 21.0
    - elixir: 1.8.0
      otp_release: 22.0

    # Elixir 1.9 with OTP 20-22
    - elixir: 1.9.0
      otp_release: 20.0
    - elixir: 1.9.0
      otp_release: 21.0
    - elixir: 1.9.0
      otp_release: 22.0


sudo: false
before_install:
  - cd teacher_component
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
